-- Script para insertar todas las Obras Sociales
-- Centro de Odontología - Sistema de Gestión de Turnos

-- Insertar obras sociales
INSERT INTO "ObrasSociales" (nombre, createdAt, updatedAt) VALUES
('Ioma', NOW(), NOW()),
('Osmecon', NOW(), NOW()),
('Casa Circulo 51', NOW(), NOW()),
('Particular', NOW(), NOW()),
('Galeno', NOW(), NOW()),
('Recetas', NOW(), NOW()),
('Assist Dent', NOW(), NOW()),
('Amebpba Circulo 22', NOW(), NOW()),
('Poder Judicial', NOW(), NOW()),
('Sancor Salud', NOW(), NOW()),
('Staff Medico', NOW(), NOW()),
('A M F F A', NOW(), NOW()),
('America Servicios', NOW(), NOW()),
('Jerarquicos Salud', NOW(), NOW()),
('Ospib Roisa', NOW(), NOW()),
('Imp Roisa', NOW(), NOW()),
('Ospit Textiles Copago Roisa', NOW(), NOW()),
('Avalian 16', NOW(), NOW()),
('Osamoc Roisa', NOW(), NOW()),
('Doctored 500 Roisa', NOW(), NOW()),
('Doctored 505', NOW(), NOW()),
('Doctored 1000', NOW(), NOW()),
('Prevencion Salud Circulo', NOW(), NOW()),
('Servicio Penitenciario Federal', NOW(), NOW()),
('Accord Salud', NOW(), NOW()),
('Pami', NOW(), NOW()),
('Privamed 770', NOW(), NOW()),
('Privamed 440', NOW(), NOW()),
('Privamed 330', NOW(), NOW()),
('Privamed 200', NOW(), NOW()),
('Privamed 100', NOW(), NOW()),
('Privamed 1000', NOW(), NOW()),
('Colegio De Escribanos', NOW(), NOW()),
('Federada Salud', NOW(), NOW()),
('Osmiss Copago Roisa', NOW(), NOW()),
('Ospep Roisa', NOW(), NOW()),
('Doctored Premium Copago', NOW(), NOW()),
('Clero', NOW(), NOW()),
('Bienestar Salud Copago Roisa', NOW(), NOW()),
('Ospfp Pintura Roisa', NOW(), NOW()),
('Visitar Consulmed Copago', NOW(), NOW()),
('Apres Consulmed', NOW(), NOW()),
('Omint Consulmed', NOW(), NOW()),
('Dosuba Consulmed', NOW(), NOW()),
('Ensalud Consulmed', NOW(), NOW()),
('Jardineros Consulmed', NOW(), NOW()),
('Osalara Consulmed', NOW(), NOW()),
('Osptv Sat Consulmed', NOW(), NOW()),
('Sadaic Consulmed', NOW(), NOW()),
('Ostel Telefonicos Consulmed', NOW(), NOW()),
('Ospiqyp Quimica Y Petrolera Consulmed', NOW(), NOW()),
('Asmepriv Consulmed', NOW(), NOW()),
('Andar Consulmed', NOW(), NOW()),
('Visitar Consulmed', NOW(), NOW()),
('Osim Consulmed', NOW(), NOW()),
('Osdop Consulmed', NOW(), NOW()),
('Igualdad Salud Roisa', NOW(), NOW()),
('Premedic', NOW(), NOW()),
('Premedic 100', NOW(), NOW()),
('Premedic 200', NOW(), NOW()),
('Premedic 300', NOW(), NOW()),
('Premedic 400 500', NOW(), NOW()),
('Salud 360 Redsom', NOW(), NOW()),
('Saber Salud Redsom Copago', NOW(), NOW()),
('A Osblyca Cueros Y Anexos', NOW(), NOW()),
('Privamed 880 Exento', NOW(), NOW()),
('Privamed 880 Grav', NOW(), NOW()),
('Medicus', NOW(), NOW()),
('Medife', NOW(), NOW()),
('Amffa Mutualistas Farmaceuticos', NOW(), NOW());

-- Verificar la inserción
SELECT COUNT(*) as total_obras_sociales FROM "ObrasSociales";
